
name: CD
on:
  push:
    branches:
      - main
jobs:
  windows-deploy:
    runs-on: windows-latest
    name: Windows Deployment
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Installing Dependencies
        run: npm install
      - name: Building and Deploying
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: npm run electron:build -- --win -p always